run:
  timeout: 5m

linters:
  disable-all: true
  enable:
  - gofmt
  - goimports
  - revive
  - misspell
  - unused
  - gocyclo
  - govet
  - unconvert
  - goconst
  - gosec
  - lll

linters-settings:
  revive:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0

  lll:
    line-length: 120
    tab-width: 8
